version: '3'

services:
  postgres:
    container_name: db_postgres
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
       - ./postgres:/postgres               
    env_file: docker-compose.env
  
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "8888:80"
    networks:
      - postgres
    env_file: docker-compose.env

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: